services:
  qwenproxy:
    build: .
    container_name: qwenproxy
    ports:
      - "3091:3000"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./qwen_profiles:/app/qwen_profiles
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
